--- app_data
CREATE USER app_data IDENTIFIED BY "FCDIZ8CeA37TlUQ"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--- app_code
CREATE USER app_code IDENTIFIED BY "9XzBljPWT7mgapB"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY "S82kiA4iwIgr5rX"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--- app_user
CREATE USER app_user IDENTIFIED BY "SJUyyN1hpGyF73F"
ENABLE EDITIONS;